services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace

  db:
    image: "postgres:16"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "SenateDev2026!"
      POSTGRES_DB: senate
    volumes:
      - senate-postgres:/var/lib/postgresql/data

volumes:
  senate-postgres:
