import os

JWT_SECRET = os.getenv("JWT_SECRET", "5s/BxwmuFt0WzdxpW3GYCEPodB+wItRp40QlFhMCNus=")
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM", "HS256")
ACCESS_TOKEN_EXPIRE_HOURS = int(os.getenv("ACCESS_TOKEN_EXPIRE_HOURS", 24))
